members = """KAVYASREE ANDE
ASFIYA BASITH
HANEEN
SKAND GUPTA
YESHASWINI BHEEMREDDY
SHAIK NIKHAT TARANNUM
RADHIKA JAIN
MEGHANA KALAKUNTLA
SHIVANI VERMA
SAMEER JHARIYA
GYANA SAI REDDY
AGARSHIKA RAMESH
JAYADEEP SRIKAR
G AKHIL REDDY
ANURAG
SHUBHAM PATTNAIK
PRASUN PARIJAT"""

print(members.splitlines())